import { Notification } from '../models/notification.model';

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    notificationId: '1',
    userId: 'user1',
    title: 'Driver Assigned',
    message: 'Rajesh Kumar has been assigned to your pickup request #REQ001',
    type: 'DriverAssigned',
    relatedEntityType: 'PickupRequest',
    relatedEntityId: 'req001',
    isRead: false,
    priority: 'High',
    createdAt: new Date(Date.now() - 5 * 60000),
  },
  {
    notificationId: '2',
    userId: 'user1',
    title: 'Driver En Route',
    message: 'Your driver is on the way to your pickup location',
    type: 'DriverEnRoute',
    relatedEntityType: 'PickupRequest',
    relatedEntityId: 'req002',
    isRead: false,
    priority: 'Urgent',
    createdAt: new Date(Date.now() - 15 * 60000),
  },
  {
    notificationId: '3',
    userId: 'user1',
    title: 'Pickup Completed',
    message: 'Your plastic bottles pickup has been completed successfully. Weight: 15 kg',
    type: 'PickupCompleted',
    relatedEntityType: 'PickupRequest',
    relatedEntityId: 'req003',
    isRead: false,
    priority: 'Normal',
    createdAt: new Date(Date.now() - 2 * 3600000),
  },
  {
    notificationId: '4',
    userId: 'user1',
    title: 'Payment Approved',
    message: '₹362.50 has been approved for your completed pickup REQ003',
    type: 'PaymentApproved',
    relatedEntityType: 'Payment',
    relatedEntityId: 'pay001',
    isRead: true,
    priority: 'Normal',
    createdAt: new Date(Date.now() - 5 * 3600000),
  },
  {
    notificationId: '5',
    userId: 'user1',
    title: 'Payment Transferred',
    message: '₹362.50 has been transferred to your account',
    type: 'PaymentPaid',
    relatedEntityType: 'Payment',
    relatedEntityId: 'pay001',
    isRead: false,
    priority: 'High',
    createdAt: new Date(Date.now() - 8 * 3600000),
  },
  {
    notificationId: '6',
    userId: 'user1',
    title: 'New Review Received',
    message: 'You received a 5-star review: "Excellent service! Very professional."',
    type: 'NewReview',
    relatedEntityType: 'Review',
    relatedEntityId: 'rev001',
    isRead: true,
    priority: 'Normal',
    createdAt: new Date(Date.now() - 24 * 3600000),
  },
  {
    notificationId: '7',
    userId: 'user1',
    title: 'Request Created',
    message: 'Your pickup request for cardboard has been submitted successfully',
    type: 'RequestCreated',
    relatedEntityType: 'PickupRequest',
    relatedEntityId: 'req004',
    isRead: true,
    priority: 'Normal',
    createdAt: new Date(Date.now() - 3 * 24 * 3600000),
  },
  {
    notificationId: '8',
    userId: 'user1',
    title: 'System Announcement',
    message:
      'RecycleHub will undergo scheduled maintenance on Sunday, 2 AM - 4 AM. Services may be temporarily unavailable.',
    type: 'SystemAnnouncement',
    relatedEntityType: undefined,
    relatedEntityId: undefined,
    isRead: true,
    priority: 'High',
    createdAt: new Date(Date.now() - 5 * 24 * 3600000),
  },
  {
    notificationId: '9',
    userId: 'user1',
    title: 'Welcome to RecycleHub!',
    message: 'Thank you for joining RecycleHub. Start your first pickup request to earn rewards!',
    type: 'Welcome',
    relatedEntityType: undefined,
    relatedEntityId: undefined,
    isRead: true,
    priority: 'Normal',
    createdAt: new Date(Date.now() - 7 * 24 * 3600000),
  },
];
